讀取資料

In [1]:
import numpy as np
import pandas as pd

file1 = 'db2020_hw5_ptt_mobilecomm.csv'
ptt20 = pd.read_csv(filepath_or_buffer=file1, error_bad_lines=False)
ptt20 = ptt20.dropna()
ptt20.index = range(0, 15231, 1)
ptt20

b'Skipping line 3642: expected 10 fields, saw 11\nSkipping line 10138: expected 10 fields, saw 11\nSkipping line 16424: expected 10 fields, saw 11\nSkipping line 18109: expected 10 fields, saw 11\nSkipping line 22897: expected 10 fields, saw 11\nSkipping line 32399: expected 10 fields, saw 12\n'

,id,p_type,s_area_id,title,author,comment_count,page_url,post_time,content,sentiment
0,1555058867705_PTT02R,bbs,WH_F0001_1579,[新聞] MTK 屢敗屢戰，年底將推出 7nm 處理器再,dan512215,52,http://www.ptt.cc/bbs/MobileComm/M.1555058243....,9012-04-12 16:37:21,MTK 屢敗屢戰，年底將推出 7nm 處理器再挑機\n\n\n\nMTK 屢敗屢戰，年底將推...,M
1,1577809081131_PTT02R,bbs,WH_F0001_1579,[心得] 2019年最後一天5G試用心得,young52177,121,http://www.ptt.cc/bbs/MobileComm/M.1577808834....,2020-01-01 00:13:52,跨年主管早放我下班\n發現平常等公車的站牌附近停了一台5G車子\n\nhttps://i.i...,P
2,1577809626223_PTT02R,bbs,WH_F0001_1579,[問題] U11 ig限時動態震動,teddy9685,0,http://www.ptt.cc/bbs/MobileComm/M.1577809324....,2020-01-01 00:22:02,剛換電池拿回來後\n\n發了幾張ig限時動態\n\n感覺比之前震動模糊程度增加不少\n\n想...,M
3,1577810538134_PTT02R,bbs,WH_F0001_1579,[討論] 2019年下半年度Opensignal調查結果,power4444w,14,http://www.ptt.cc/bbs/MobileComm/M.1577810057....,2020-01-01 00:34:15,先祝各位大大新年快樂\n2019年過了，但是還是得看看2019年誰在混、誰有進步\n\nht...,M
4,1577812562318_PTT02R,bbs,WH_F0001_1579,[問題] 紅米note 8 pro 如何刪除預設app,hijacker,12,http://www.ptt.cc/bbs/MobileComm/M.1577812479....,2020-01-01 01:14:37,"機型：紅米 note 8 pro 國際版MIUI,已刷twrp\n\n沒有root，我直接在...",M
...,...,...,...,...,...,...,...,...,...,...
15226,1608097967604_PTT02R,bbs,WH_F0001_1579,[問題] ZF5Z 內建App自動消失,XXXXCOCK,3,http://www.ptt.cc/bbs/MobileComm/M.1608097800....,2020-12-16 13:49:58,家裡長輩手機是ZF5Z\n\n最近這幾個禮拜出現內建App自動消失的現象\n\n上次是原生時...,M
15227,1608098729434_PTT02R,bbs,WH_F0001_1579,[問題] Google Pixel手機保固內維修問題,skyHuan,68,http://www.ptt.cc/bbs/MobileComm/M.1608098544....,2020-12-16 14:02:20,家父的手機是Pixel 3a\n\n昨天突然螢幕全黑不能顯示，但背景程式似乎仍有在執行\n\...,N
15228,1608100234598_PTT02R,bbs,WH_F0001_1579,[問題] 手錶血氧偵測準確度？,pantani,23,http://www.ptt.cc/bbs/MobileComm/M.1608100085....,2020-12-16 14:27:58,因為自己有在登山\n對於有血氧偵測功能的智慧手錶非常感興趣\n所以昨天試了三星 蘋果 G...,M
15229,1608102151675_PTT02R,bbs,WH_F0001_1579,[情報] Asus Zenfone 7 聖誕節優惠！,asdf3164,37,http://www.ptt.cc/bbs/MobileComm/M.1608101846....,2020-12-16 14:57:24,https://i.imgur.com/5PqCooc.jpg\n折扣3000\n還能搭配舊...,M
15230,1608107365386_PTT02R,bbs,WH_F0001_1579,[問題] 挑選行動電源+一些問題,mathgang,5,http://www.ptt.cc/bbs/MobileComm/M.1608107002....,2020-12-16 16:23:20,因為有爬百岳的習慣，需要買一個大容量的行動電源\n我的手機是Google Pixel 5 ，...,M

In [2]:
file2 = 'db2020_hw5_dcard_3c.csv'
dcard20 = pd.read_csv(filepath_or_buffer=file2, error_bad_lines=False)
dcard20 = dcard20.dropna()
dcard20.index = range(0, 17745, 1)
dcard20

b'Skipping line 1848: expected 10 fields, saw 11\nSkipping line 8228: expected 10 fields, saw 14\nSkipping line 13213: expected 10 fields, saw 11\nSkipping line 13215: expected 10 fields, saw 16\n'

,id,p_type,s_area_id,title,author,comment_count,page_url,post_time,content,sentiment
0,1577809016769_F02,forum,WH_F0116_0017,想救照片,國立臺北大學/M,1,https://www.dcard.tw/f/3c/p/232800099,2020-01-01 00:00:03,上一支手機進水壞掉\n主機板、電池跟充電孔都燒壞了\n以前照片都存在記憶卡\n但有些圖片會被...,N
1,1577821370306_F02,forum,WH_F0116_0017,海盜船鍵盤,長榮大學/M,0,https://www.dcard.tw/f/3c/p/232801559,2020-01-01 03:30:49,想請問海盜船k68的鍵盤 \n沒出青軸了嗎 我上網查了好多間都只有紅軸\n可是他好像有出紅軸...,M
2,1577840467231_F02,forum,WH_F0116_0017,Aser筆電大比拼,嶺東科技大學/F,9,https://www.dcard.tw/f/3c/p/232802003,2020-01-01 08:37:22,因為我近期要買筆電，\n其實我買筆電的要求不高..\n只要是可以做報告，\n然後可以玩Ste...,M
3,1577842252118_F02,forum,WH_F0116_0017,Mac book pro待機一晚掉很多電，是google害的嗎？,朝陽科技大學/F,3,https://www.dcard.tw/f/3c/p/232802099,2020-01-01 09:20:27,想請問一下各位用mac的大大\n自己電腦有下載估狗瀏覽器嗎？\n因為前幾天發現自己的電腦才剛...,M
4,1577844080771_F02,forum,WH_F0116_0017,想賣掉手邊的華碩5z,中國科技大學/M,0,https://www.dcard.tw/f/3c/p/232802188,2020-01-01 09:57:20,不知道這邊可不可po買賣文\n\n8g/256 銀色 現在應該是沒貨\n\n購入空機為價19...,M
...,...,...,...,...,...,...,...,...,...,...
17740,1608105362094_F02_dcard,forum,WH_F0116_0017,三星明年傳推4款摺疊機 平價版有望先登場,國立臺灣大學/M,0,https://www.dcard.tw/f/3c/p/234992272,2020-12-16 15:55:05,https://i.imgur.com/cYSw6iO.png\n除了年底將亮相的小米11，...,M
17741,1608105363441_F02_dcard,forum,WH_F0116_0017,iphone 入塵,元智大學資訊工程學系/M,0,https://www.dcard.tw/f/3c/p/234992268,2020-12-16 15:53:58,這幾天發現手機後鏡怪怪的\n一直有一個黑點在\n如圖\n\nhttps://i.imgur....,N
17742,1608107172023_F02_dcard,forum,WH_F0116_0017,換電信的問題,黎明技術學院/F,0,https://www.dcard.tw/f/3c/p/234992407,2020-12-16 16:20:45,請問大家我台哥大合約到期了要攜碼換中華但12月帳單已經來了現在用下去就是1月的帳單了這樣我換...,M
17743,1608107173100_F02_dcard,forum,WH_F0116_0017,別買惡魔手機殼,景文科技大學/F,0,https://www.dcard.tw/f/3c/p/234992335,2020-12-16 16:05:33,跟朋友前陣子換手機 兩個人都買惡魔二代防摔殼\n他的用一兩個禮拜沒摔到 靜音按鈕附近的地方就...,N
17744,1608109016659_F02_dcard,forum,WH_F0116_0017,請問8plus更新 不喜勿入,國立高雄大學/M,0,https://www.dcard.tw/f/3c/p/234992458,2020-12-16 16:31:26,如題 \nIPhone 8 plus 64GB\n目前版本13.4\n請問更新到14以上的朋...,M

建立dataframe

In [3]:
# 建立計分dataframe
models= {
    'name' : ['iPhone 12', 'iPhone 11', 'iPhone SE', 'Zenfone 7', 'Pixel 4', 'U20', 
              'Reno 4', 'C3', 'A21s', 'A71', 'A31', 'S20', 'Note 20', 'Xperia 5', 'X50'],
    'titlenum(ptt)' : [0] * 15,
    'contentnum(ptt)' : [0] * 15,
    'commentnum(ptt)' : [0] * 15,
    'discussion(ptt)' : [0] * 15
}

model_df = pd.DataFrame(models)

"""
各欄位依序為:
title數(ptt), content數(ptt), commentnum(ptt), 討論度(ptt)
"""

# 建立各機型名稱高相關詞彙
model_alias_dict = {
    'iPhone 12': ['i12', 'iphone12', 'iphone 12', 'iPhone12', 'iPHONE 12', 'iPhone 12'],
    'iPhone 11': ['i11', 'iphone11', 'iphone 11', 'iPhone11', 'iPHONE 11', 'iPhone 11'],
    'Zenfone 7': ['ZF7', 'zf7', 'Zenfone 7'],
    'Pixel 4': ['p4', 'P4', 'Pixel 4'],
    'Note 20': ['N20', 'Note20', 'Note 20'],
    'Xperia 5': ['Sony 5', 'Xperia 5'],
    'A21s': ['A21S', 'A21s', 'A21'],
    'S20': ['S20', 's20']
}

# 重新編排index
model_df.index = ['iPhone 12', 'iPhone 11', 'iPhone SE', 'Zenfone 7', 'Pixel 4', 'U20', 
              'Reno 4', 'C3', 'A21s', 'A71', 'A31', 'S20', 'Note 20', 'Xperia 5', 'X50']
model_df

,name,titlenum(ptt),contentnum(ptt),commentnum(ptt),discussion(ptt)
iPhone 12,iPhone 12,0,0,0,0
iPhone 11,iPhone 11,0,0,0,0
iPhone SE,iPhone SE,0,0,0,0
Zenfone 7,Zenfone 7,0,0,0,0
Pixel 4,Pixel 4,0,0,0,0
U20,U20,0,0,0,0
Reno 4,Reno 4,0,0,0,0
C3,C3,0,0,0,0
A21s,A21s,0,0,0,0
A71,A71,0,0,0,0
A31,A31,0,0,0,0
S20,S20,0,0,0,0
Note 20,Note 20,0,0,0,0
Xperia 5,Xperia 5,0,0,0,0
X50,X50,0,0,0,0

分析標題、內容並統計結果

In [4]:
for model in model_df['name']:
    # 各機型在ptt的四項指標
    title_ptt = 0
    content_ptt = 0
    commentnum_ptt = 0
    discussion_ptt = 0

    for i in range(15231):  # 過濾全部文章
        title = ptt20.at[i, 'title']
        content = ptt20.at[i, 'content']
        commentnum = ptt20.at[i, 'comment_count']
        
        if model in model_alias_dict:
            for alias in model_alias_dict[model]:  # 跑過所有別稱
                try:
                    if title.find(alias) != -1:
                        title_ptt += 1
                        commentnum_ptt += int(commentnum)

                    if content.find(alias) != -1:
                        content_ptt += 1
                        if title.find(alias) == -1:  # 只有內文有出現
                            commentnum_ptt += int(commentnum)

                # 避免未知錯誤
                except AttributeError:
                    continue

                except ValueError:
                    continue
        else:
            try:
                if title.find(model) != -1:
                    title_ptt += 1
                    commentnum_ptt += int(commentnum)
            
                if content.find(model) != -1:
                    content_ptt += 1
                    if title.find(model) == -1:  # 只有內文有出現
                        commentnum_ptt += int(commentnum)
            # 避免未知錯誤
            except AttributeError:
                continue

            except ValueError:
                continue

    discussion_ptt = 10*title_ptt + 5*content_ptt + commentnum_ptt  # 計算討論度
    
    # 將此機型資料貼到dataframe
    model_df.at[model, 'titlenum(ptt)'] = title_ptt
    model_df.at[model, 'contentnum(ptt)'] = content_ptt
    model_df.at[model, 'commentnum(ptt)'] = commentnum_ptt
    model_df.at[model, 'discussion(ptt)'] = int(discussion_ptt)

model_df

,name,titlenum(ptt),contentnum(ptt),commentnum(ptt),discussion(ptt)
iPhone 12,iPhone 12,341,658,47237,53937
iPhone 11,iPhone 11,155,730,46914,52114
iPhone SE,iPhone SE,118,258,21301,23771
Zenfone 7,Zenfone 7,64,143,12853,14208
Pixel 4,Pixel 4,260,619,39148,44843
U20,U20,28,66,4727,5337
Reno 4,Reno 4,12,22,919,1149
C3,C3,10,113,4636,5301
A21s,A21s,16,59,2600,3055
A71,A71,106,271,11889,14304
A31,A31,19,55,1819,2284
S20,S20,528,1071,64251,74886
Note 20,Note 20,116,284,16943,19523
Xperia 5,Xperia 5,59,99,9110,10195
X50,X50,67,132,4743,6073

In [5]:
model_df = model_df.drop('name', axis=1)
model_df = model_df.sort_values(['discussion(ptt)'], ascending=False)
model_df

           titlenum(ptt)  contentnum(ptt)  commentnum(ptt)  discussion(ptt)
S20                  528             1071            64251            74886
iPhone 12            341              658            47237            53937
iPhone 11            155              730            46914            52114
Pixel 4              260              619            39148            44843
iPhone SE            118              258            21301            23771
Note 20              116              284            16943            19523
A71                  106              271            11889            14304
Zenfone 7             64              143            12853            14208
Xperia 5              59               99             9110            10195
X50                   67              132             4743             6073
U20                   28               66             4727             5337
C3                    10              113             4636             5301
A21s                  16               59             2600             3055
A31                   19               55             1819             2284
Reno 4                12               22              919             1149

以下為iphone12競品分析，建立需要的df和演算法

In [6]:
# 競爭者計分dataframe
competitors= {
    'name' : ['iPhone 11', 'iPhone SE', 'Zenfone 7', 'Pixel 4', 'U20', 
              'Reno 4', 'C3', 'A21s', 'A71', 'A31', 'S20', 'Note 20', 'Xperia 5', 'X50'],
    '共同提及' : [0] * 14,
}

competitors_df = pd.DataFrame(competitors)

# 競爭者的高相關詞彙
competitors_alias_dict = {
    'iPhone 11': ['i11', 'iphone11', 'iphone 11', 'iPhone11', 'iPHONE 11', 'iPhone 11'],
    'Zenfone 7': ['ZF7', 'zf7', 'Zenfone 7'],
    'Pixel 4': ['p4', 'P4', 'Pixel 4'],
    'Note 20': ['N20', 'Note20', 'Note 20'],
    'Xperia 5': ['Sony 5', 'Xperia 5'],
    'A21s': ['A21S', 'A21s', 'A21'],
    'S20': ['S20', 's20']
}

# i12的高相關詞彙
i12_alias = ['i12', 'iphone12', 'iphone 12', 'iPhone12', 'iPHONE 12', 'iPhone 12']

# 重新編排index
competitors_df.index = ['iPhone 11', 'iPhone SE', 'Zenfone 7', 'Pixel 4', 'U20', 
              'Reno 4', 'C3', 'A21s', 'A71', 'A31', 'S20', 'Note 20', 'Xperia 5', 'X50']
# 清理資料
competitors_df = competitors_df.drop('name', axis=1)
competitors_df

           共同提及
iPhone 11     0
iPhone SE     0
Zenfone 7     0
Pixel 4       0
U20           0
Reno 4        0
C3            0
A21s          0
A71           0
A31           0
S20           0
Note 20       0
Xperia 5      0
X50           0

In [7]:
for competitor in competitors_df.index:
    for i in range(15231):
        article = ptt20.at[i, 'content']  # 每篇文章
        
        for i12 in i12_alias:
            if competitor in competitors_alias_dict:  # 競品有別稱
                for com in competitors_alias_dict[competitor]:
                    if article.find(i12) != -1 and article.find(com) != -1:  # 兩者被共同提及
                        competitors_df.at[competitor, '共同提及'] += 1
            else:  # 競品無別稱
                if article.find(i12) != -1 and article.find(competitor) != -1:  # 兩者被共同提及
                        competitors_df.at[competitor, '共同提及'] += 1

competitors_df

           共同提及
iPhone 11   197
iPhone SE    46
Zenfone 7     0
Pixel 4      29
U20           5
Reno 4        2
C3            5
A21s          5
A71           4
A31           2
S20          78
Note 20      46
Xperia 5     19
X50           6

In [10]:
competitors_df = competitors_df.sort_values(['共同提及'], ascending=False)
competitors_df

           共同提及
iPhone 11   197
S20          78
iPhone SE    46
Note 20      46
Pixel 4      29
Xperia 5     19
X50           6
U20           5
C3            5
A21s          5
A71           4
Reno 4        2
A31           2
Zenfone 7     0